name: trivico
description: "A trivia game."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2

dependencies:
  confetti: ^0.7.0
  device_preview: ^1.2.0
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  html_unescape: ^2.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
