name: trivico
description: "A trivia game."
publish_to: "none"
version: 1.1.1+4

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2

dependencies:
  confetti: ^0.8.0
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.6.1
  google_fonts: ^6.2.1
  html_unescape: ^2.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  step_progress_indicator: ^1.0.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - .env
    - shorebird.yaml
