// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8WJs_FD4MyIOjP5jYHbsKzdDq1nyCLg',
    appId: '1:214754300312:android:82aa42526234aa3acadbed',
    messagingSenderId: '214754300312',
    projectId: 'trivico-f97ee',
    storageBucket: 'trivico-f97ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFWovvbwoPjlj5d2AvC7F2GujtebbWSw',
    appId: '1:214754300312:ios:149da6eec36fcd7ccadbed',
    messagingSenderId: '214754300312',
    projectId: 'trivico-f97ee',
    storageBucket: 'trivico-f97ee.appspot.com',
    iosBundleId: 'com.carbon.trivico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAp3w6VHTDxCM_9MFkLatnh0W70sKJ38s',
    appId: '1:214754300312:web:e71557cdab2ed587cadbed',
    messagingSenderId: '214754300312',
    projectId: 'trivico-f97ee',
    authDomain: 'trivico-f97ee.firebaseapp.com',
    storageBucket: 'trivico-f97ee.appspot.com',
    measurementId: 'G-45M80582QY',
  );
}
