name: Flutter CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - uses: cedvdb/action-flutter-build-android@v1
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"

      - name: Archive APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.0
          files: build/app/outputs/flutter-apk/app-release.apk