name: Flutter CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Release APK
        uses: oberhauser-dev/flutter-release-action@v0
        with:
          app-name: 'trivico'
          token: ${{ github.ACTIONS_TOKEN }}
          android-keystore-file-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          android-keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"