name: Flutter version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION=$(grep -o 'version:.*' pubspec.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Print extracted version
        run: echo "The extracted version is ${{ env.version }}"